### ISSUE TITLE
implémenter dans le code le déclenchement de bruitages

### ISSUE THREAD

**Issue by sylvainpolletvillard** [myriagonofficial/alpha#10]
- à l'apparition d'une carte
        - lorsqu'on manipule la carte (balayage, etc)
        - musique de fond en début d'ère

**Comment by sylvainpolletvillard** [comment]
lib choisie: howler.js ; il gère plein de trucs cool, notamment la spatialisation du son, si ça vous donne des idées...

j'ai codé vite fait un système de channels pour mute/tweak indépendamment les SFX, voix et la musique

**Comment by ElSenorDuvivier** [comment]
Je regarde pour implémenter un truc du genre :
![2019-05-11_03h01_15](https://user-images.githubusercontent.com/50497727/57563852-5ede4800-73a3-11e9-9070-e375fbb32381.png)

Je vais regarder si je parviens à trouver une astuce de mon côté pour "augmenter" la fonction "sprite" pour lui faire jouer la queue de reverb pour faire des belles boucles !! :)

**Comment by ElSenorDuvivier** [comment]
High! Jme disais en essayant un autre format comme l'ogg pour voir s'il boucle un peu plus proprement naturellement, l'idéal je pense, restant le système décrit ci dessus.

**Comment by sylvainpolletvillard** [comment]
je vois ce que tu veux faire et je vois comment le faire facilement vincent, mais la queue devra probablement être dans un fichier audio séparé.

dans l'idée, le son qui boucle aura un callback onEnd qui fera un check, à chaque tour de boucle on regarde si on est en train de passer à l'ère suivante, auquel cas on stoppe la loop et on enchaîne avec la queue. En jouant sur les timings, la transition peut être invisible.

Le seul problème de cette technique est que si l'on change d'ère au tout début de la loop, le joueur devra potentiellement attendre toute la loop + le temps de la queue, c'est à dire assez longtemps pour que ce soit chiant.

La solution de simplicité serait un fadeOut/fadeIn ou cross-fade, qu'on peut déclencher à n'importe quel moment et dynamiquement, sans besoin de nouveau fichier audio. Mais je comprendrais que vous ayez d'autres intentions, surtout que c'est un projet musical

**Comment by sylvainpolletvillard** [comment]
[General Tips for Game Developers.pdf](https://github.com/myriagonofficial/alpha/files/3169512/General.Tips.for.Game.Developers.pdf)

je partage les notes que j'avais sur les faiblesses du mp3 pour les loops

**Comment by ElSenorDuvivier** [comment]
Yes super bien vue ! Eh bien je vais essayer de lister les comportement potentiellement voulus en plus du système de boucle et crossfade que tu décris, on est déjà pas mal si on a la boucle et le crossfade!!!

**Comment by sylvainpolletvillard** [comment]
cross-fade c'est easy peasy avec la lib howler, on peut partir là dessus et décider plus tard si vous voulez améliorer cette partie là ou pas, selon vos ambitions

**Comment by ElSenorDuvivier** [comment]
Tiens pour te filer un truc que j'connais :) mon éditeur préféré de sons : https://www.boomlibrary.com
