### ISSUE TITLE
Permettre le déclenchement d'un deck sur une condition particulière

### ISSUE THREAD

**Issue by LeDetrogneur** [myriagonofficial/alpha#12]
L'idée c'est qu'à la fin du premier deck (conditions environnementales), une espèce émerge : on choisit de démarrer le deck qui correspond à l'espèce en question. 

Pour le passage du second deck (ère de développement primaire) au troisième (technologie avancée), l'idée c'est qu'on ait abouti un certain nombre de stories en décrochant une technologie à la clef (par exemple pour le peuple nomade, il développe la cartographie), et qu'on déclenche directement le troisième deck, qui concerne toujours la même espèce.

**Comment by sylvainpolletvillard** [comment]
comment on choisit l'espèce du coup ?

**Comment by LeDetrogneur** [comment]
Je pense que pour l’ere Primaire on peut fixer un nombre de story achevées (pas toutes, histoire de réserver des surprises aux prochaines itérations), genre 60% des story jouées. 
Pour la suivante, il s’agirait d’avoir réunis des conditions d'acquisition de technologies : à chaque arc narratif on débloque ou non une techno, et si on en a 5/10 alors hop on passe à l’ere Technologie. Si on a déroulé toutes les cartes sans avoir décroché ces 5 technos alors c’est le gameover par forfait en gros. On a écrit des brouillons d’arcs pour la question de la sédentarité et de la religion, si tu veux avoir une vague idée.
