### ISSUE TITLE
Audio new version

### ISSUE THREAD

**Issue by 20008484** [myriagonofficial/alpha#15]
Nouvelle version dispo pour les fichiers audio sources 👍 
mus_gardienDuTemps_01.ogg
mus_gardienDuTemps_02.ogg
mus_gardienDuTemps_03.ogg
mus_menu_01.ogg

Lien : 
https://drive.google.com/open?id=1kBI9pV5TDpAa0VXSB6CuUybPIDmK7mEF

**Comment by LeDetrogneur** [comment]
C'est fait =)
