### ISSUE TITLE
Retour au menu

### ISSUE THREAD

**Issue by 20008484** [myriagonofficial/alpha#20]
Euch bouton retour au menu ne fait pas réapparaître le bouton pour commencer une autre partie . 

1
![image](https://user-images.githubusercontent.com/50743116/67583981-fdd9df00-f74c-11e9-8aee-77e7c4e171e3.png)

2
![image](https://user-images.githubusercontent.com/50743116/67584023-0df1be80-f74d-11e9-8ef2-1c6100e6558e.png)

**Comment by sylvainpolletvillard** [comment]
corrigé normalement
