### ISSUE TITLE
Màj audio

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#22]
Les fichiers **Master** ne sont plus utilisés, plus besoin de les charger dans ch'bousin car ils sont lourds sa mère !
(mus_lullMaster_01 mus_apexMatser_01 mus_headwayMaster_01 mus_primalMaster_01 mus_agonyMaster_01)

Les fichiers **vox_gardienDuTemps*** sont nouveaux (à remplaçouse :p )

Le fichier **mus_lullLoop_01.ogg** est nouveau il doit prendre la place de **mus_lullMaster_01.ogg** (ancien)

D'une manière génèrale si c'est pas chronophage (passe pas de temps là dessus, on peut le faire une bonne fois pour toutes vers la fin), tu peux réimporter tous les fichiers audio sources depuis le drive pour reprendre en compte les quelques modifications de timing/niveau de ci de là ^^

Des bisous bisax !

**Comment by sylvainpolletvillard** [comment]
Tous les fichiers dans le dossier audio ne sont pas chargés, on vient seulement prendre ceux qui nous intéressent (déclarés ici: https://github.com/myriagonofficial/alpha/blob/master/src/audio.js#L68)

J'ai tout remis dans la boîte, je relivre ce soir
