### ISSUE TITLE
Gestion de l'apparition des jauges

### ISSUE THREAD

**Issue by LeDetrogneur** [myriagonofficial/alpha#23]
Dans la version actuelle, la branche apparaît en une seule fois et se peuple de feuilles et de fleurs sur la même carte, on n'identifie pas clairement que fleurs = bonheur & feuilles = environnement.

J'imagine quelque chose du genre : 
> la branche est visible dès le départ
> showIndicateurBonheur(); fait apparaître des fleurs, elles disparaissent lorsqu'on clique sur la réponse (puisque le bonheur doit commencer à quasi zéro, dans l'idée qu'au départ la civilisation n'existe quasi pas)
> showIndicateurEnvironnement(); fait apparaître les feuilles, qui restent.

J'ai constaté que pour l'instant il n'y a que "CompteurEnvironnement" alors je n'y ai pas touché =)

**Comment by sylvainpolletvillard** [comment]
les deux compteurs ont été fusionnés en un seul composant depuis le changement de compteur.

J'ai fait apparaitre et tomber 50 fleurs après 1 seconde au moment de showIndicateurBonheur(). Si on les fait tomber au clic sur la réponse, je dois gérer le cas où le joueur clique plus vite que le délai d'apparition, et ça fait pas très beau et ça mord sur le début du chapitre Primal.

**Comment by sylvainpolletvillard** [comment]
J'ai aussi changé l'ordre des cartes pour que le compteur bonheur soit présenté après celui environnemental, puisqu'on doit afficher la branche avant les fleurs
