### ISSUE TITLE
Audio - nouveaux sons

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#24]
Dispo ici : https://drive.google.com/open?id=1kBI9pV5TDpAa0VXSB6CuUybPIDmK7mEF 

**gui_transitionEntreEres_01.ogg** --> à lancer lors d'une transition entre deux ères (en même temps que ch'panneau)

4 autres fichiers moins important (voir à ne pas mettre)
**vox_prophete_01.ogg
vox_prophete_02.ogg
vox_prophete_03.ogg
vox_prophete_04.ogg**
--> ne pas perdre de temps là dessus, petite tentative de délire voix, à lancer à chaque nouvelle question venant d'un prophète (en lançant au hasard un des quatre fichiers)

**Comment by sylvainpolletvillard** [comment]
Bon je fais rien avec les voix alors, t'assumes pas ?
