### ISSUE TITLE
Audio Dev : création de boucle aléatoire

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#27]
**Amis du soir bonsoir !**

**L'idée** : chaque boucle de musique est déclinée en 3 versions un peu différentes. L’objectif serait de boucler aléatoirement sur une des 3 variations.
![image](https://user-images.githubusercontent.com/50497727/68063897-38c3b000-fd15-11e9-9608-cdc05fa3b1b9.png)

**Voici les fichiers ajoutés dans le drive pour opérer** 👍  
[mus_agonyLoop_01 - mus_agonyLoop_03 ]
[mus_apexLoop_01 - mus_apexLoop_03]
[mus_headwayLoop_01 - mus_headwayLoop_03]
[mus_primalLoop_01 - mus_primalLoop_03]

**Egalement quelques fichiers mis à jours** : 
[vox_gardienDuTemps_01 - vox_gardienDuTemps_08 ]
mus_menu_01

**Le lien du dossier** : https://drive.google.com/open?id=1kBI9pV5TDpAa0VXSB6CuUybPIDmK7mEF

**Comment by sylvainpolletvillard** [comment]
Pour bien  comprendre, tu veux boucler sur une des 3 versions tirée aléatoirement ou lire en boucle la liste des 3 versions triée aléatoirement ?

Si on change de morceau, ça veut dire que je n'utilise plus l'option loop de l'API web audio, mais que je déclenche la lecture du second morceau a la fin du premier. Il est possible que la transition ne soit pas aussi fluide du coup, même en prechargeant les morceaux. Je dois rester ca

**Comment by ElSenorDuvivier** [comment]
La deuxième option, dans notre cas : "lire en boucle la liste des 3 versions triée aléatoirement"
Et si c'est la galère de ouf niveau technique ou même que ça prends trop de temps à faire, je peux revenir sur un seul fichier. On s'appel demaing ou quand ça t'arrange s'tu veux : 07 81 12 81 84

**Comment by sylvainpolletvillard** [comment]
Okay j'ai donc codé ça: 

`playMusicRandomSequence(['mus_apex_01', 'mus_apex_02', 'mus_apex_03'])`

un ordre aléatoire est tiré, par exemple: 2 → 3 → 1

cette séquence aléatoire est ensuite répétée indéfiniment:
2 → 3 → 1 → 2 → 3 → 1 → 2 → 3 →1...

Sur Primal ça a l'air ok le temps de transition. Je publie ça et te laisse tester @ElSenorDuvivier

**Comment by sylvainpolletvillard** [comment]
by the way, bien joué pour avoir pondu des variations aussi cool. Je suis fan de celles d'Apex notamment, le mélange de genres est dingue ! :+1:
