### ISSUE TITLE
Audio : Idée au sujet des boucles

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#28]
Hello les zamis !

J'ai eu une idée pour les boucles de musique dans ALPHA, cependant, au vue de la complexité d'explication, j'ai préféré la faire en vidéo pour essayer d'être le plus clair possible.

Encore une fois si c'est chaud niveau réalisation technique, on partira sur une option plus simple ! Aucun soucis !

Voici le lien de la vidéo explicative non répertoriée : https://youtu.be/cdx80-fQq3c

**Comment by ElSenorDuvivier** [comment]
A 6min 20 la démo en audio si jamais le blabla seul est trop chiant ^^

**Comment by sylvainpolletvillard** [comment]
Ouais un crossfade linéaire sur la totalité de la durée quoi ;p

J'ai fini de coder, ça rend pas mal mais le coup de tirer une variation aléatoire à chaque fois, fait que c'est assez au courant de se taper 2, 3 voire 4 fois la même variation d'affilée. Je te laisse tester mais je ferais bien en sorte qu'on puisse pas enchaîner deux fois la même variation. Après c'est toi l'artiste ;)
