### ISSUE TITLE
Fond en fonction des étapes

### ISSUE THREAD

**Issue by FabienOrlita** [myriagonofficial/alpha#29]
à chaque étape de la civilsation,

Pour Primal, Headway, Apex et Agony il y a un fond différent sur les écrans introductifs et dans la fond pendant la partie, ici c'est toujours celui de Headway.

ils sont ici :
https://drive.google.com/drive/u/2/folders/1u5gAiXyFx8-r-AZIxBcoD9E0C3X9FuSn

et là : 
https://drive.google.com/drive/u/2/folders/1uzacVRlcnthZZCXilU0AO6m9eiQy1oAL

Merci :)

**Comment by sylvainpolletvillard** [comment]
@FabienOrlita je suis un peu confus sur l'image que je dois utiliser. Qu'est-ce que je fais avec les calques transparents ? Par dessus l'image de base ça rend pas beau, les éléments se chevauchent

**Comment by sylvainpolletvillard** [comment]
Je me suis pas servi des calques transparents du coup, c'est le papier beige semi-transparent qui se met par-dessus
