### ISSUE TITLE
transition audio - mus_gardienDuTemps

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#34]
Hello !! Voici un détail des fondus et retards de déclenchement qui me semblent rendre à peu prêt correctement :

![image](https://user-images.githubusercontent.com/50497727/68529765-3c050000-0302-11ea-8180-1d605d3ff179.png)

![image](https://user-images.githubusercontent.com/50497727/68529959-3e685980-0304-11ea-8cd9-02cc5919d2d3.png)

**Comment by sylvainpolletvillard** [comment]
T'es sûr de ton coup vincent ? on ne peut pas prévoir le moment où le joueur change de carte, du coup les crossfade peuvent être déclenchés n'importe quand, ça risque de sonner assez mal je pense

**Comment by ElSenorDuvivier** [comment]
Ouaip j'suis à peu prêt sûr!! J'allais balancer un truc hasardeux jusqu'au
moment ou j'ai essayé dans mon daw pour me rendre compte que j'allais
demander du brun XD !! Si c'est assez simples de faire précisément les
timing décrits, tu peux y aller, si c'est genre chaud de par exemple avoir
le décalage de 500ms au lancement de la boucle suivante, ou n'importe
qu'elle autre difficulté, laisse en l'état, c'est parfaitement audible
ainsi ;)

**Comment by sylvainpolletvillard** [comment]
OK avec l'écart de 500ms c'est plutôt pas mal !
