### ISSUE TITLE
transition audio -  mus_primalLoop - vox_gardienDuTemps_08

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#35]
Re !

Une idée qui me semble bien en guise de transition audio pour justifier un peu plus la réapparition des gardiens du temps qui blablatent :
![image](https://user-images.githubusercontent.com/50497727/68530026-c2224600-0304-11ea-8db0-0bf9e18ec247.png)

**Comment by sylvainpolletvillard** [comment]
le fadeout sur le son de la voix ça va être plus compliqué , j'ai fait en sorte que tous les sons se coupent quand on change de chapitre sinon ça se superpose quand tu cliques trop vite et c'est pas agréable à l'oreille

**Comment by sylvainpolletvillard** [comment]
En plus la voix est super courte en vrai, genre 5 secondes, je sais pas si ça vaut le coup de mettre un fadeout de 1 seconde là dedans. Et ça reste bizarre que le gardien se remette à parler à la fin du chapitre.

**Comment by ElSenorDuvivier** [comment]
pour le gardien qui reparle à la fin, si ça t'a perturbé, on peut
l'enlever, ça veut dire que globalement ca risque de perturber pleins
d'autres gens :p !!!! Pour le fondu d'une seconde, c'était plus dans le
sens générale lorsqu'on a un stop sur un son ou sur un ensemble de sons,
essayer d'adoucir un peu le stop qui parfois m'a semblé un petit peu sec ;)
pareil si c'est chaud ça faire t'emmerde pas, c'est présentable ainsi !!

**Comment by sylvainpolletvillard** [comment]
je l'ai fait pour les musiques mais pour les voix je pense que c'est l'effet désiré de "couper sec", on lui ferme le clapet on clique avant qu'il a fini :)

**Comment by ElSenorDuvivier** [comment]
bonne idouse !! je suis pour !! je demande ayssi du brun, faut rester
critique ;)
