### ISSUE TITLE
transition audio - idée générale sur les fondus de sortie

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#36]
Voici une idée générale qui me semble assez propre pour la gestion des transtions : lorsqu'un stop est déclenché, toujours faire un fondu d'une seconde pour éviter une coupure trop brève 👍 

![image](https://user-images.githubusercontent.com/50497727/68530114-918edc00-0305-11ea-8bca-d0b65b0af81a.png)

**Comment by sylvainpolletvillard** [comment]
Il y avait déjà un fadeout de 400ms à l'arrêt de la musique, je vais le pousser à 1 seocnde
