### ISSUE TITLE
transition audio - fondu d'entrée sur le système de boucle musical

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#37]
It's me again,

Petite précision sur le fondu d'entrée du système de boucle musical en crossfade 👍 
![image](https://user-images.githubusercontent.com/50497727/68530455-86897b00-0308-11ea-833d-1345aa99f841.png)

**Comment by sylvainpolletvillard** [comment]
Alors là par contre tu m'as perdu.

Comment je fais un fondu d'entrée de 8s sur la variation alors qu'il y a déjà un crossfade descendant sur la durée de la variation pour introduire la suivante ? Je peux pas "superposer" les fade

**Comment by ElSenorDuvivier** [comment]
oui exact !! je ne sais pas si c'est possible techniquement ou pas à chaque
fois du coup je balance l'idée. En fait l'idée sous jacente derrière ce
fondu d'entrée sur le système de boucles c'est que tu peux faire à la fois
un fondu de sortie sur le fichier avec en parallèle un fondu d'entrée sur
le groupe de pistes musique. ( dans notre cas notre groupe de pistes
musique comporte deux pistes servant au système de crossfade, ce groupe à
lui son propre volume, qu'on peut faire arriver en fondu d'entrée
également) si c'po possible, te caille pas le lait !! C'est bien en l'État
!!

**Comment by sylvainpolletvillard** [comment]
Le truc c'est que tu veux faire un fondu entrant sur une piste qui est déjà en fondu de sortie dès son démarrage. Donc le volume monte et descend à la fois, mais pas à la même vitesse ?

Je sais pas faire de superposition de fondus contradictoires, à moins de tout calculer moi-même en multipliant les coefficients de volume. Ça me paraît chaud là

**Comment by ElSenorDuvivier** [comment]
haha !! ma foie n'y perds pas de temps !! c'est présentable ainsi !! :)

**Comment by sylvainpolletvillard** [comment]
on laisse béton donc !
