### ISSUE TITLE
Sur la dernière carte qui supposément vide les jauges, des fleurs apparaissent à nouveau (je n'en avais plus du tout)

### ISSUE THREAD

**Issue by LeDetrogneur** [myriagonofficial/alpha#41]

**Comment by sylvainpolletvillard** [comment]
bah il faut bien fleurir la tombe

*sort*

**Comment by sylvainpolletvillard** [comment]
je crois que c'est parce que tu es arrivé à un nombre négatif dans le compteur de bonheur. Je vais m'assurer que ça ne puisse pas se produire
