### ISSUE TITLE
bug affichage bonus

### ISSUE THREAD

**Issue by FabienOrlita** [myriagonofficial/alpha#42]
Après une fin de partie, je clique sur le bouton des bonus, puis sur mon bonus et la page s'affiche de cette manière : 
![Capture d’écran 2019-11-11 à 17 47 49](https://user-images.githubusercontent.com/57533598/68605384-980b8800-04ac-11ea-824d-84c27958535b.png)

**Comment by sylvainpolletvillard** [comment]
je parviens pas à reproduire sur FF/Chrome avec diverses résolutions.... ça a ptet déjà été fix ? je vais relivrer et je te laisse vérifier si c'est encore reproductible
