### ISSUE TITLE
Image - Préchargement pour les transitions entre ères

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#43]
Hi !

Lors de l'affichage d'une nouvelle ère, j'sais pas si c'est possible de précharger l'image de fond pour éviter qu'elle ne saute lorsqu'elle s'affiche. (chaque nouvelle ère fait cette petite "saute"

C'est quand on affiche les ères à ce moment là par exemple : 

![image](https://user-images.githubusercontent.com/50497727/68605569-ecaf0300-04ac-11ea-9d3a-158b07706c2c.png)

**Comment by sylvainpolletvillard** [comment]
yes je les ajoute à la liste de préchargement, ça devrait améliorer un peu les choses
