### ISSUE TITLE
MAJ Fond Apex

### ISSUE THREAD

**Issue by FabienOrlita** [myriagonofficial/alpha#44]
Je me suis planté sur les fonds pour Apex pour le chapitrage et pour le fond du jeu.
J'ai mis à jour le fichier dans le drive ! Désolé !

ici pour le fond durant la partie: https://drive.google.com/drive/u/2/folders/1uzacVRlcnthZZCXilU0AO6m9eiQy1oAL

ici pour le chapitrage:
https://drive.google.com/drive/u/2/folders/1u5gAiXyFx8-r-AZIxBcoD9E0C3X9FuSn

**Comment by sylvainpolletvillard** [comment]
Pour info je me sers que de l'image que tu appelles "chapitrage", le fond beige étant semi-opaque
