### ISSUE TITLE
Audio - son d'interface

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#45]
Hi !

Puissiez-vous remplacer le son de survol de ces éléments (actuellement gui_menuSurvolBoutonJouer_01.ogg)  avec le son plus court (gui_survolUnChoix_01.ogg)

Les éléments en question en image : 
![image](https://user-images.githubusercontent.com/50497727/68774277-2575e600-062d-11ea-8762-354b2b1e21b4.png)
![image](https://user-images.githubusercontent.com/50497727/68774326-39214c80-062d-11ea-9bdd-6e22e07cbc3d.png)

**Comment by sylvainpolletvillard** [comment]
fait !
