### ISSUE TITLE
Image manquante - Exploration - Saison - et quelques autres

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#47]
![image](https://user-images.githubusercontent.com/50497727/68778102-f82c3680-0632-11ea-85ed-b2218b786927.png)

![image](https://user-images.githubusercontent.com/50497727/68778202-1f830380-0633-11ea-8d1e-2de343e23b0c.png)

![image](https://user-images.githubusercontent.com/50497727/68778509-94563d80-0633-11ea-9ee6-ff4557f5ad17.png)

![image](https://user-images.githubusercontent.com/50497727/68778421-74267e80-0633-11ea-9543-dc2ea1565846.png)

**Comment by LeDetrogneur** [comment]
C'est corrigé normalement !
