### ISSUE TITLE
Audio - système de boucle musicale

### ISSUE THREAD

**Issue by ElSenorDuvivier** [myriagonofficial/alpha#49]
Hello !

Voilà ce que j'ai pu observé :
- une fois que chaque boucle a été jouée une fois, il n'y a plus de décalage rythmique perceptible --> le système fonctionne parfaitement
- quand une boucle n'a jamais été jouée depuis le rechargement de la page Web (CTRL + R) alors la boucle vient créer un décalage rythmique la première fois qu'elle apparaît, puis si elle est rappellée, plus de problème.

Analyse : 
- il doit y avoir une relation entre le décalage et le chargement/préchargement d'une boucle musicale

Idée  : 
Est-ce qu'on peut précharger toutes les boucles en mémoire en début de partie ? et est-ce que cela changerait le comportement ? (je ne sais guère ma foie)

Merci pour tout ce que tu fais !
Si t'as pas le temps/le courage de traiter c'pô graffe !! ;)

**Comment by sylvainpolletvillard** [comment]
normalement elles sont préloadées mais pas entièrement, jusqu'à ce que le navigateur estime pouvoir commencer à les lire et télécharger le reste en background sans interruption
je peux pousser le préchargement jusqu'à télécharger le morceau complet, ça va ralentir encore le chargement mais ptet résoudre le problème
